# Generated by Django 5.2.6 on 2025-09-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(max_length=500)),
                (
                    "ingredients",
                    models.TextField(
                        help_text="List ingredients with measurements, one per line"
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        help_text="Step-by-step instructions including preparation and cooking time if needed"
                    ),
                ),
                ("image", models.ImageField(upload_to="recipe_images/")),
                ("is_draft", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
            },
        ),
    ]
